[tool.flake8]
exclude = [
    '.git',
    '__pycache__',
    'docs',
    'migrations',
    'venv',
    'env',
]
max-line-length = 100

[tool.isort]
profile = "black"
src_paths = ["src/project"]
skip_glob = ["*/migrations/*"]

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | venv
  | env
  | docs
)/
'''
